export { default as Dashboard } from './Dashboard/index'
export { default as CreateUser } from './createUser.jsx'
export { default as UpdateUser } from './updateUser.jsx'
export { default as DeleteUser } from './deleteUser.jsx'
export { default as ChangePassword } from './changePassword.jsx'
export { default as Accounts } from './Accounts/index'
export { default as Category } from './Categories/index'
export { default as Product } from './Products/index'
export { default as Profile} from './Profiles/index'